import {StyleSheet} from "react-native";
import hairlineWidth = StyleSheet.hairlineWidth;


export default StyleSheet.create({
    searchContainer: {
        flexDirection: 'row',
        height: 50,
        borderRadius: 10,
        margin: 10,
    },
    searchButton: {
        position: 'relative',
        top: 15,
        left: 5,
        // padding: 10,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#064851',
        height: 45,
        width: 45,
        borderRadius: 50,
    },
    searchInput: {
        // backgroundColor: '#fefefe',
        // height: 50,
        // padding: 10,
        // // margin: 10,
        // borderRadius: 10,
        // flex : 1,
        fontSize: 15,
    },
    resultsText: {
        paddingLeft: 10,
        fontSize: 20,
    },
    itemBloc: {
        flexDirection: 'column',
        justifyContent: 'center',
        marginTop: 10,
        height: 84,
        backgroundColor: '#fff',
        padding: 10,
        borderRadius: 15,
    },
    resultsContainer: {
        flex: 1,
        padding: 10,
    },
    icon:{
        padding: 10,
    },
    ingredientListContainer: {
        flex: 1,
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: -25,
    },
    ingreBox: {
        backgroundColor: '#d9d9d9',
        padding: 10,
        margin: 5,
        borderRadius: 10,
        height: 100,
        width: 100,
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: StyleSheet.hairlineWidth,
        // textAlign: 'center',
    },
    contentContainer: {
        alignItems: 'flex-start',
        justifyContent: 'center',
    },
    loading: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(155,155,155,0.52)',
        ...StyleSheet.absoluteFillObject,
        zIndex: 100,

    },
    modalContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(155,155,155,0.52)',
        ...StyleSheet.absoluteFillObject,
        zIndex: 100,
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        width: '100%',
        padding: 10,
        backgroundColor: '#064851',
        borderTopLeftRadius: 10,
        borderTopRightRadius: 10,
    },
    modalTitle: {
        fontSize: 20,
    },
    modalBody: {
        backgroundColor: '#fff',
        width: '100%',
        padding: 10,
        borderBottomLeftRadius: 10,
        borderBottomRightRadius: 10,
    },
    modalText: {
        fontSize: 15,
    },
    modalFilter: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        width: '100%',
        padding: 10,
        // backgroundColor: '#064851',
        borderTopLeftRadius: 10,
        borderTopRightRadius: 10,
    },
    modalFilterButton: {
        padding: 10,
        alignItems: 'center',
        justifyContent: 'center',
        // backgroundColor: '#064851',
        height: 45,
    },
    filterButton: {
        // position: 'absolute',
        padding: 10,
        alignItems: 'center',
        justifyContent: 'flex-end',
        flexDirection: 'row',
        // backgroundColor: '#064851',
        height: 45,
        width: 45,
        // borderRadius: 50,
    }

});